### ISSUE TITLE
Consider replacing uSpec with Rspec

### ISSUE THREAD

**Issue by acook** [acook/config_module#18]
When I started this project, Rspec was a lumbering monolith, and many times larger than config_module's codebase, so I used my testing micro-framework [uSpec](https://github.com/acook/uspec) instead. 

Rspec has seen some serious improvements over the intervening time and some of its features might come in handy. 

Basically the question that needs to be answered is if there's a clear win in using Rspec over uSpec.

**Comment by Spaceghost** [comment]
RSpec is nice because rails developers know it really well. minitest is nice because rubyists know it even if they've never used the library before.

RSpec seems a better direction if you want to make it easy for people to contribute.

**Comment by acook** [comment]
@Spaceghost true, but uSpec is "just Ruby". The syntax isn't weird - because there's almost none. 

Here's some example code (from [config_module's specs](https://github.com/acook/config_module/blob/master/spec/config_module_spec.rb)):

~~~ruby
spec 'modules extended with ConfigModule will load configurations' do
  ExampleConfig.foo == 'bar'
end

spec 'modules extended with ConfigModule have "namespace" methods' do
  ExampleConfig.methods.include? :namespace
end
~~~

**Comment by acook** [comment]
Here's the output up on [Tavis-CI](https://travis-ci.org/acook/config_module/jobs/83402103):
<img width="936" alt="screen shot 2015-10-02 at 19 23 23" src="https://cloud.githubusercontent.com/assets/71984/10260381/6259ca44-693a-11e5-9640-c70722a7d8ab.png">

**Comment by Spaceghost** [comment]
I'm not against it. It looks pretty simple and clean and I get how I'd use it just from seeing a single test.

**Comment by acook** [comment]
uSpec seems to be doing just fine right now.
