### ISSUE TITLE
ConfigModule should exit gracefully if the configuration file isn't found

### ISSUE THREAD

**Issue by acook** [acook/config_module#43]
Or optionally it should ignore that it is missing?

Currently it just crashes with an exception and no additional help.

**Comment by BrianHawley** [comment]
Crashing with an unhandled exception is not graceful. Raising a custom exception intentionally is much better, because it acknowledges the reality that this is usually a really bad situation, but gives people something specific to catch and ignore when it's not.

**Comment by acook** [comment]
Agreed!
